In [142]:
import torch

In [143]:
x = torch.arange(12)

In [144]:
print(x)

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])


In [145]:
x.shape

torch.Size([12])

In [146]:
x.numel()

12

In [147]:
X = x.reshape(3,4)

In [148]:
X

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [149]:
Y = torch.arange(12).reshape(3,4)
Y


tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

In [150]:
torch.cat((X,Y),dim=1)#按列拼接 三维dim等于2也行 

tensor([[ 0,  1,  2,  3,  0,  1,  2,  3],
        [ 4,  5,  6,  7,  4,  5,  6,  7],
        [ 8,  9, 10, 11,  8,  9, 10, 11]])

In [151]:
X==Y

tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

In [152]:
X.sum()

tensor(66)

In [153]:
import pandas as pd

In [154]:
data = pd.read_csv("data_set/从11个特征预测学生的测试分数.csv")

In [155]:
data

school school_setting school_type classroom teaching_method  n_student  \
0     ANKYI          Urban  Non-public       6OL        Standard       20.0   
1     ANKYI          Urban  Non-public       6OL        Standard       20.0   
2     ANKYI          Urban  Non-public       6OL        Standard       20.0   
3     ANKYI          Urban  Non-public       6OL        Standard       20.0   
4     ANKYI          Urban  Non-public       6OL        Standard       20.0   
...     ...            ...         ...       ...             ...        ...   
2128  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2129  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2130  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2131  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2132  ZOWMK          Urban      Public       ZBH        Standard       30.0   

     student_id  gender                             lunch  pretest  posttest  
0         2FHT3  Female                  Does not qualify     62.0      72.0  
1         3JIVH  Female                  Does not qualify     66.0      79.0  
2         3XOWE    Male                  Does not qualify     64.0      76.0  
3         556O0  Female                  Does not qualify     61.0      77.0  
4         74LOE    Male                  Does not qualify     64.0      76.0  
...         ...     ...                               ...      ...       ...  
2128      T8LSK  Female                  Does not qualify     39.0      55.0  
2129      VNP26  Female  Qualifies for reduced/free lunch     38.0      46.0  
2130      YDR1Z  Female  Qualifies for reduced/free lunch     45.0      51.0  
2131      YUEIH    Male  Qualifies for reduced/free lunch     46.0      53.0  
2132      ZVCQ8    Male  Qualifies for reduced/free lunch     41.0      48.0  

[2133 rows x 11 columns]

In [156]:
inputs,outputs = data.iloc[:,0:9],data.iloc[:,10]
inputs


school school_setting school_type classroom teaching_method  n_student  \
0     ANKYI          Urban  Non-public       6OL        Standard       20.0   
1     ANKYI          Urban  Non-public       6OL        Standard       20.0   
2     ANKYI          Urban  Non-public       6OL        Standard       20.0   
3     ANKYI          Urban  Non-public       6OL        Standard       20.0   
4     ANKYI          Urban  Non-public       6OL        Standard       20.0   
...     ...            ...         ...       ...             ...        ...   
2128  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2129  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2130  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2131  ZOWMK          Urban      Public       ZBH        Standard       30.0   
2132  ZOWMK          Urban      Public       ZBH        Standard       30.0   

     student_id  gender                             lunch  
0         2FHT3  Female                  Does not qualify  
1         3JIVH  Female                  Does not qualify  
2         3XOWE    Male                  Does not qualify  
3         556O0  Female                  Does not qualify  
4         74LOE    Male                  Does not qualify  
...         ...     ...                               ...  
2128      T8LSK  Female                  Does not qualify  
2129      VNP26  Female  Qualifies for reduced/free lunch  
2130      YDR1Z  Female  Qualifies for reduced/free lunch  
2131      YUEIH    Male  Qualifies for reduced/free lunch  
2132      ZVCQ8    Male  Qualifies for reduced/free lunch  

[2133 rows x 9 columns]

In [157]:
#inputs = inputs.fillna(inputs.mean())#如果产生缺失的值 填充为平均值？
inputs = inputs.drop(columns=["school","classroom","student_id"],axis=1)
inputs = pd.get_dummies(inputs)
inputs

n_student  school_setting_Rural  school_setting_Suburban  \
0          20.0                     0                        0   
1          20.0                     0                        0   
2          20.0                     0                        0   
3          20.0                     0                        0   
4          20.0                     0                        0   
...         ...                   ...                      ...   
2128       30.0                     0                        0   
2129       30.0                     0                        0   
2130       30.0                     0                        0   
2131       30.0                     0                        0   
2132       30.0                     0                        0   

      school_setting_Urban  school_type_Non-public  school_type_Public  \
0                        1                       1                   0   
1                        1                       1                   0   
2                        1                       1                   0   
3                        1                       1                   0   
4                        1                       1                   0   
...                    ...                     ...                 ...   
2128                     1                       0                   1   
2129                     1                       0                   1   
2130                     1                       0                   1   
2131                     1                       0                   1   
2132                     1                       0                   1   

      teaching_method_Experimental  teaching_method_Standard  gender_Female  \
0                                0                         1              1   
1                                0                         1              1   
2                                0                         1              0   
3                                0                         1              1   
4                                0                         1              0   
...                            ...                       ...            ...   
2128                             0                         1              1   
2129                             0                         1              1   
2130                             0                         1              1   
2131                             0                         1              0   
2132                             0                         1              0   

      gender_Male  lunch_Does not qualify  \
0               0                       1   
1               0                       1   
2               1                       1   
3               0                       1   
4               1                       1   
...           ...                     ...   
2128            0                       1   
2129            0                       0   
2130            0                       0   
2131            1                       0   
2132            1                       0   

      lunch_Qualifies for reduced/free lunch  
0                                          0  
1                                          0  
2                                          0  
3                                          0  
4                                          0  
...                                      ...  
2128                                       0  
2129                                       1  
2130                                       1  
2131                                       1  
2132                                       1  

[2133 rows x 12 columns]

In [158]:
a = torch.ones((2,5,4))
print(a)
print(a[0])
print(a[0][0])


tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])
tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])
tensor([1., 1., 1., 1.])


In [159]:
a.sum(axis=0)

tensor([[2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.],
        [2., 2., 2., 2.]])

In [160]:
a = torch.ones((2,5,4))
a.sum(axis=0,keepdim=True)

tensor([[[2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.],
         [2., 2., 2., 2.]]])

In [171]:
x = torch.arange(4.0,requires_grad=True)

In [173]:
x

tensor([0., 1., 2., 3.], requires_grad=True)

In [174]:
y = 2 * torch.dot(x,x)
y

tensor(28., grad_fn=<MulBackward0>)

In [175]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [176]:
x.grad == 4 * x

tensor([True, True, True, True])

In [177]:
 x.grad.zero_()

tensor([0., 0., 0., 0.])

In [189]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad


tensor([1., 1., 1., 1.])